project:
  type: website
  output-dir: docs
  resources: 
    - resume.pdf

website:
  title: "Ryan Marangattu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.pdf
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

